"""Keep bootstrap/runtime repo hygiene expectations from regressing."""

from __future__ import annotations

from pathlib import Path
import re
import subprocess

import pytest

from scripts import tpp_migration_guard


def _git_ls_files(pattern: str) -> list[str]:
    result = subprocess.run(
        ["git", "ls-files", pattern],
        check=True,
        capture_output=True,
        text=True,
    )
    return [line for line in result.stdout.splitlines() if line]


def _all_tracked_files() -> list[str]:
    result = subprocess.run(
        ["git", "ls-files"],
        check=True,
        capture_output=True,
        text=True,
    )
    return [line for line in result.stdout.splitlines() if line]


def test_no_node_modules_tracked_anywhere() -> None:
    """node_modules/ must never be tracked in git anywhere in the repo.

    Install JS dependencies with `npm ci` from the relevant package-lock.json.
    """
    tracked = [p for p in _all_tracked_files() if "node_modules" in p]
    assert not tracked, (
        f"Found {len(tracked)} tracked node_modules path(s). "
        "Remove them with `git rm -r --cached <path>/node_modules/` and ensure "
        "node_modules/ is listed in .gitignore without exceptions.\n"
        f"First offending path: {tracked[0]}"
    )


def test_gitignore_covers_node_modules() -> None:
    gitignore = Path(".gitignore").read_text(encoding="utf-8")
    assert "node_modules/" in gitignore, (
        ".gitignore must include a `node_modules/` rule so generated JS dependencies "
        "are never accidentally committed."
    )
    assert "!.github/scripts/node_modules/" not in gitignore, (
        ".gitignore must not exempt .github/scripts/node_modules/ — "
        "workflow script dependencies should be installed with `npm ci`, not tracked."
    )


def test_github_scripts_has_package_lock() -> None:
    lock = Path(".github/scripts/package-lock.json")
    assert lock.exists(), (
        ".github/scripts/package-lock.json must exist so CI can run `npm ci` "
        "to install workflow script dependencies reproducibly."
    )


def test_makefile_has_test_target() -> None:
    makefile = Path("Makefile").read_text(encoding="utf-8")
    assert "test:" in makefile, (
        "Makefile must have a 'test' target so agents and contributors have a documented "
        "default Python test command. Add: test:\\n\\tpython -m pytest"
    )


def test_makefile_uses_npm_ci_for_frontend() -> None:
    makefile = Path("Makefile").read_text(encoding="utf-8")
    assert "npm --prefix frontend ci" in makefile, (
        "Makefile install target must use `npm --prefix frontend ci` (not `npm install`) "
        "so local installs are reproducible from the lock file."
    )


def test_egg_info_is_not_tracked() -> None:
    tracked = _git_ls_files("trip_planner.egg-info/")
    assert not tracked, (
        "trip_planner.egg-info/ must not be tracked in git; it is generated by "
        "`pip install -e .` and varies by environment. "
        "Run `git rm -r --cached trip_planner.egg-info/` and ensure *.egg-info/ is in .gitignore."
    )


def test_gitignore_excludes_egg_info() -> None:
    gitignore = Path(".gitignore").read_text(encoding="utf-8")
    assert "*.egg-info/" in gitignore or ".egg-info/" in gitignore, (
        ".gitignore must exclude *.egg-info/ directories so generated package metadata "
        "is not accidentally committed."
    )


def test_readme_documents_default_python_test_command() -> None:
    readme = Path("README.md").read_text(encoding="utf-8")
    assert "make test" in readme, (
        "README.md must document the default Python test command ('make test') so "
        "contributors know how to run the unit test suite in a clean checkout."
    )


def test_readme_documents_local_bootstrap_and_optional_integrations() -> None:
    readme = Path("README.md").read_text(encoding="utf-8")

    expected_snippets = [
        "python -m venv .venv",
        "npm --prefix frontend ci",
        "frontend/node_modules",
        "TRIP_PLANNER_DATABASE_URL",
        "VITE_API_BASE_URL",
        "VITE_GOOGLE_MAPS_EMBED_API_KEY",
        "TPP_BASE_URL",
        "TPP_ACCESS_TOKEN",
        "TPP_OIDC_PROVIDER",
        "They do not prove live Google Maps rendering or remote Travel-Plan-Permission transport",
    ]

    for snippet in expected_snippets:
        assert snippet in readme, f"README.md must document {snippet!r}."


def test_tpp_renames_require_recorded_sub_decision_in_pr_body() -> None:
    """Block TPP git mv operations until the PR body records B-1/B-2/B-3."""
    if not tpp_migration_guard.is_pr_context():
        pytest.skip(
            "TPP rename guard requires pull-request diff context; post-merge "
            "canonical-layout checks cover main."
        )

    ok, message = tpp_migration_guard.enforce_guard()
    assert ok, message


def test_no_tpp_files_remain_under_legacy_app_tree() -> None:
    """TPP modules must not remain in trip_planner/app after canonical migration."""
    legacy_tpp_paths = _git_ls_files("trip_planner/app/**/*tpp*.py")
    assert not legacy_tpp_paths, (
        "Found TPP-related Python files under trip_planner/app. "
        "Move them to trip_planner/integrations/tpp or document intentional shims in the PR body.\n"
        f"Offending paths: {', '.join(legacy_tpp_paths[:20])}"
    )


def test_no_production_tpp_imports_from_legacy_app_namespaces() -> None:
    """Keep production TPP imports on the canonical integrations path."""
    pattern = re.compile(
        r"^\s*(from|import)\s+trip_planner\.app\.(services|models|clients)\.[^\n#]*tpp",
        re.IGNORECASE,
    )
    offenders: list[str] = []

    for path_str in _git_ls_files("trip_planner/**/*.py"):
        path = Path(path_str)
        for index, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            if pattern.search(line):
                offenders.append(f"{path_str}:{index}")

    assert not offenders, (
        "Production TPP imports must not use trip_planner.app.services/models/clients. "
        "Use trip_planner.integrations.tpp instead.\n"
        f"Offending locations: {', '.join(offenders[:20])}"
    )
