"""Keep bootstrap/runtime repo hygiene expectations from regressing."""

from __future__ import annotations

from pathlib import Path
import subprocess


def _git_ls_files(pattern: str) -> list[str]:
    result = subprocess.run(
        ["git", "ls-files", pattern],
        check=True,
        capture_output=True,
        text=True,
    )
    return [line for line in result.stdout.splitlines() if line]


def test_root_node_modules_is_not_tracked() -> None:
    tracked = _git_ls_files("node_modules/**")
    assert not tracked, (
        "Root node_modules must stay untracked; install app JS dependencies with "
        "`npm --prefix frontend install` instead."
    )


def test_gitignore_documents_expected_node_modules_layout() -> None:
    gitignore = Path(".gitignore").read_text(encoding="utf-8")

    assert "node_modules/" in gitignore
    assert "!.github/scripts/node_modules/" in gitignore
    assert "!.github/scripts/node_modules/**" in gitignore


def test_makefile_has_test_target() -> None:
    makefile = Path("Makefile").read_text(encoding="utf-8")
    assert "test:" in makefile, (
        "Makefile must have a 'test' target so agents and contributors have a documented "
        "default Python test command. Add: test:\\n\\tpython -m pytest"
    )


def test_egg_info_is_not_tracked() -> None:
    tracked = _git_ls_files("trip_planner.egg-info/")
    assert not tracked, (
        "trip_planner.egg-info/ must not be tracked in git; it is generated by "
        "`pip install -e .` and varies by environment. "
        "Run `git rm -r --cached trip_planner.egg-info/` and ensure *.egg-info/ is in .gitignore."
    )


def test_gitignore_excludes_egg_info() -> None:
    gitignore = Path(".gitignore").read_text(encoding="utf-8")
    assert "*.egg-info/" in gitignore or ".egg-info/" in gitignore, (
        ".gitignore must exclude *.egg-info/ directories so generated package metadata "
        "is not accidentally committed."
    )


def test_readme_documents_default_python_test_command() -> None:
    readme = Path("README.md").read_text(encoding="utf-8")
    assert "make test" in readme, (
        "README.md must document the default Python test command ('make test') so "
        "contributors know how to run the unit test suite in a clean checkout."
    )


def test_readme_documents_local_bootstrap_and_optional_integrations() -> None:
    readme = Path("README.md").read_text(encoding="utf-8")

    expected_snippets = [
        "python -m venv .venv",
        "npm --prefix frontend install",
        "frontend/node_modules",
        "TRIP_PLANNER_DATABASE_URL",
        "VITE_API_BASE_URL",
        "VITE_GOOGLE_MAPS_EMBED_API_KEY",
        "TPP_BASE_URL",
        "TPP_ACCESS_TOKEN",
        "TPP_OIDC_PROVIDER",
        "They do not prove live Google Maps rendering or remote Travel-Plan-Permission transport",
    ]

    for snippet in expected_snippets:
        assert snippet in readme, f"README.md must document {snippet!r}."
