version: 1

default_agent: codex

# Shared keepalive marker prefix (agent-agnostic)
keepalive_marker_prefix: agent-keepalive

agents:
  codex:
    runner_workflow: .github/workflows/reusable-codex-run.yml
    required_secrets:
      - CODEX_AUTH_JSON
    branch_prefix: codex/issue-
    ui_mentions_allowed: false
    automation_logins:
      - chatgpt-codex-connector
    readiness_candidates:
      - chatgpt-codex-connector
    capabilities:
      pr_keepalive: true
      pr_autofix: true
      belt: true
      verifier_checkbox: true

  claude:
    runner_workflow: .github/workflows/reusable-claude-run.yml
    required_secrets:
      - CLAUDE_AUTH_JSON
    branch_prefix: claude/issue-
    ui_mentions_allowed: false
    automation_logins:
      - stranske-automation-bot
    readiness_candidates:
      - stranske-automation-bot
    capabilities:
      pr_keepalive: true
      pr_autofix: true
      belt: true
      verifier_checkbox: true
