"""Normalized destination and option-building contracts."""

from .destinations import (
    ADJACENCY_KINDS,
    AdjacencyKind,
    EXPERIENCE_SENTIMENTS,
    MOBILITY_MODES,
    OPERATIONAL_NOTE_IMPACTS,
    OPERATIONAL_NOTE_KINDS,
    PLACE_KINDS,
    PLACE_RELATIONSHIP_KINDS,
    PROVENANCE_ROLES,
    PlaceKind,
    PlaceRelationshipKind,
    SCHEMA_VERSION,
    SEASONS,
    SEASONAL_IMPACTS,
    TAG_SCOPES,
    Destination,
    DestinationGeo,
    DestinationSourceRef,
    DestinationTag,
    ExperienceSignal,
    MobilityProfile,
    NearbyDestinationRef,
    OperationalNote,
    PlaceHierarchyRef,
    SeasonalSignal,
)

__all__ = [
    "ADJACENCY_KINDS",
    "AdjacencyKind",
    "EXPERIENCE_SENTIMENTS",
    "MOBILITY_MODES",
    "OPERATIONAL_NOTE_IMPACTS",
    "OPERATIONAL_NOTE_KINDS",
    "PLACE_KINDS",
    "PLACE_RELATIONSHIP_KINDS",
    "PROVENANCE_ROLES",
    "PlaceKind",
    "PlaceRelationshipKind",
    "SCHEMA_VERSION",
    "SEASONS",
    "SEASONAL_IMPACTS",
    "TAG_SCOPES",
    "Destination",
    "DestinationGeo",
    "DestinationSourceRef",
    "DestinationTag",
    "ExperienceSignal",
    "MobilityProfile",
    "NearbyDestinationRef",
    "OperationalNote",
    "PlaceHierarchyRef",
    "SeasonalSignal",
]
