"""Canonical shared planning contracts for destinations, trips, options, and objectives."""

from __future__ import annotations

from importlib import import_module

from .destinations import (
    ADJACENCY_KINDS,
    EXPERIENCE_SENTIMENTS,
    EXPANSION_MODES,
    MOBILITY_MODES,
    OPERATIONAL_NOTE_IMPACTS,
    OPERATIONAL_NOTE_KINDS,
    PLACE_CONTEXT_BOUNDARIES,
    PLACE_CONTEXT_ROLES,
    PLACE_KINDS,
    PLACE_RELATIONSHIP_KINDS,
    PROVENANCE_ROLES,
    SCHEMA_VERSION,
    SEASONS,
    SEASONAL_IMPACTS,
    TAG_SCOPES,
    AdjacencyKind,
    Destination,
    DestinationGeo,
    DestinationSourceRef,
    DestinationTag,
    ExperienceSignal,
    MobilityProfile,
    NearbyDestinationRef,
    OperationalNote,
    PlaceContext,
    PlaceContextRole,
    PlaceHierarchyRef,
    PlaceKind,
    PlaceRelationshipKind,
    RegionExpansionRef,
    SeasonalSignal,
)
from .objectives import (
    BudgetProtection,
    CountRange,
    DayStructureObjectives,
    DiscoveryStrategy,
    ItineraryObjectives,
    LodgingStrategy,
    MoveDensityTarget,
    QualityFloorProtection,
    RecoveryExpectations,
    TransportStrategy,
)
from .options import (
    ComparisonAxis,
    MoneyRange,
    Option,
    OptionCostSummary,
    OptionQualitySummary,
    OptionSet,
)
from .trip import (
    ProfileRefs,
    TravelerPartySummary,
    Trip,
    TripArtifactRefs,
    TripFrameSummary,
)

_LAZY_IMPORTS = {
    "ACTIVITY_AVAILABILITY_STATUSES": (".activities", "AVAILABILITY_STATUSES"),
    "ACTIVITY_FORMATS": (".activities", "ACTIVITY_FORMATS"),
    "ACTIVITY_KINDS": (".activities", "ACTIVITY_KINDS"),
    "ACTIVITY_SCHEMA_VERSION": (".activities", "SCHEMA_VERSION"),
    "ActivityBookingTerms": (".activities", "ActivityBookingTerms"),
    "ActivityCategory": (".activities", "ActivityCategory"),
    "ActivityCostSummary": (".activities", "ActivityCostSummary"),
    "ActivityEffortSummary": (".activities", "ActivityEffortSummary"),
    "ActivityFeasibility": (".activities", "ActivityFeasibility"),
    "ActivityFitSummary": (".activities", "ActivityFitSummary"),
    "ActivityOption": (".activities", "ActivityOption"),
    "ActivityQualitySummary": (".activities", "ActivityQualitySummary"),
    "ActivitySignificanceSummary": (".activities", "ActivitySignificanceSummary"),
    "ActivityTimingSummary": (".activities", "ActivityTimingSummary"),
    "ActivityValueSummary": (".activities", "ActivityValueSummary"),
    "EFFORT_LEVELS": (".activities", "EFFORT_LEVELS"),
    "INVENTORY_STATUSES": (".lodging", "INVENTORY_STATUSES"),
    "LOCATION_CONTEXTS": (".lodging", "LOCATION_CONTEXTS"),
    "LODGING_KINDS": (".lodging", "LODGING_KINDS"),
    "LodgingBookingTerms": (".lodging", "LodgingBookingTerms"),
    "LodgingCostSummary": (".lodging", "LodgingCostSummary"),
    "LodgingFeasibility": (".lodging", "LodgingFeasibility"),
    "LodgingFitSummary": (".lodging", "LodgingFitSummary"),
    "LodgingLocationSummary": (".lodging", "LodgingLocationSummary"),
    "LodgingOption": (".lodging", "LodgingOption"),
    "LodgingQualitySummary": (".lodging", "LodgingQualitySummary"),
    "LodgingRoomSummary": (".lodging", "LodgingRoomSummary"),
    "LodgingValueSummary": (".lodging", "LodgingValueSummary"),
}


def __getattr__(name: str) -> object:
    if name not in _LAZY_IMPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attribute_name = _LAZY_IMPORTS[name]
    module = import_module(module_name, __name__)
    value = getattr(module, attribute_name)
    globals()[name] = value
    return value


__all__ = [
    "ACTIVITY_AVAILABILITY_STATUSES",
    "ACTIVITY_FORMATS",
    "ACTIVITY_KINDS",
    "ACTIVITY_SCHEMA_VERSION",
    "ADJACENCY_KINDS",
    "AdjacencyKind",
    "ActivityBookingTerms",
    "ActivityCategory",
    "ActivityCostSummary",
    "ActivityEffortSummary",
    "ActivityFeasibility",
    "ActivityFitSummary",
    "ActivityOption",
    "ActivityQualitySummary",
    "ActivitySignificanceSummary",
    "ActivityTimingSummary",
    "ActivityValueSummary",
    "BudgetProtection",
    "ComparisonAxis",
    "CountRange",
    "DayStructureObjectives",
    "Destination",
    "DestinationGeo",
    "DestinationSourceRef",
    "DestinationTag",
    "DiscoveryStrategy",
    "EFFORT_LEVELS",
    "EXPERIENCE_SENTIMENTS",
    "ExperienceSignal",
    "EXPANSION_MODES",
    "INVENTORY_STATUSES",
    "ItineraryObjectives",
    "LOCATION_CONTEXTS",
    "LODGING_KINDS",
    "LodgingBookingTerms",
    "LodgingCostSummary",
    "LodgingFeasibility",
    "LodgingFitSummary",
    "LodgingLocationSummary",
    "LodgingOption",
    "LodgingQualitySummary",
    "LodgingRoomSummary",
    "LodgingStrategy",
    "LodgingValueSummary",
    "MOBILITY_MODES",
    "MobilityProfile",
    "MoneyRange",
    "MoveDensityTarget",
    "NearbyDestinationRef",
    "OPERATIONAL_NOTE_IMPACTS",
    "OPERATIONAL_NOTE_KINDS",
    "OperationalNote",
    "Option",
    "OptionCostSummary",
    "OptionQualitySummary",
    "OptionSet",
    "PlaceContext",
    "PLACE_CONTEXT_BOUNDARIES",
    "PLACE_CONTEXT_ROLES",
    "PLACE_KINDS",
    "PLACE_RELATIONSHIP_KINDS",
    "PlaceContextRole",
    "PlaceHierarchyRef",
    "PlaceKind",
    "PlaceRelationshipKind",
    "PROVENANCE_ROLES",
    "ProfileRefs",
    "QualityFloorProtection",
    "RecoveryExpectations",
    "RegionExpansionRef",
    "SCHEMA_VERSION",
    "SEASONS",
    "SEASONAL_IMPACTS",
    "SeasonalSignal",
    "TAG_SCOPES",
    "TransportStrategy",
    "TravelerPartySummary",
    "Trip",
    "TripArtifactRefs",
    "TripFrameSummary",
]
