#!/usr/bin/env python3
"""Sync shared status file .gitignore patterns to consumer repos.

This script ensures all consumer repos have the canonical .gitignore entries
for auto-generated status files that cause merge conflicts.

Usage:
    # Check what would be added (dry-run)
    python scripts/sync_status_file_ignores.py --check

    # Generate patch for a specific repo's .gitignore
    python scripts/sync_status_file_ignores.py --repo stranske/Trend_Model_Project

    # Output the canonical block to stdout
    python scripts/sync_status_file_ignores.py --print-block

The canonical patterns are defined in:
    templates/consumer-repo/.gitignore

These patterns prevent merge conflicts from:
- autofix_report_enriched.json (updated every PR)
- codex-prompt.md / codex-output.md (rebuilt every keepalive)
- keepalive-metrics.ndjson (append-only metrics)
- And other workflow-generated files
"""

from __future__ import annotations

import argparse
import base64
import binascii
import json
import logging
import subprocess
import sys
from pathlib import Path
from typing import Any, NoReturn

# Canonical status file patterns that should be ignored
# These are the minimum patterns needed to prevent merge conflicts
FALLBACK_PATTERNS: list[str] = [
    # Agent working files (HIGH conflict risk)
    "codex-prompt.md",
    "codex-output.md",
    "codex-prompt-*.md",
    "codex-output-*.md",
    "verifier-context.md",
    "verifier-diff-summary.md",
    # Autofix status files (HIGH conflict risk)
    "autofix_report_enriched.json",
    ".cosmetic-repair-summary.json",
    "ci/autofix/history.json",
    "ci/autofix/diagnostics.json",
    # Metrics/history files (MEDIUM conflict risk)
    "keepalive_status.md",
    "docs/keepalive/status/",
    "keepalive-metrics.ndjson",
    "coverage-trend-history.ndjson",
    "metrics-history.ndjson",
    "metrics-retention.ndjson",
    "residual-trend-history.ndjson",
    "archives/metrics/",
    # Build artifacts
    ".autofix-venv/",
    # PR automation generated files (MEDIUM conflict risk)
    "pr_body.md",
    # Local opener/closer lane state (MEDIUM conflict risk)
    "workloop-state.md",
    # Test/coverage artifacts
    "coverage.xml",
    # Wrong package manager artifacts (defense-in-depth)
    "Pipfile.lock",
    "poetry.lock",
    # Accidentally-committed dependency trees. The vendored-tree exceptions are retained only
    # for consumers whose package manifest deliberately uses a file:node_modules dependency.
    "node_modules/",
    "!/.github/scripts/node_modules/",
    "!/.github/scripts/node_modules/**",
]

GITIGNORE_BLOCK_HEADER = """# =============================================================================
# Workflows Consumer Repo - Shared Status Files
# =============================================================================
# Auto-generated by workflows; causes merge conflicts if committed.
# Sync from: stranske/Workflows templates/consumer-repo/.gitignore
# Validate: python scripts/sync_status_file_ignores.py --check
# =============================================================================
# Template-Version: 5
# BEGIN WORKFLOWS STATUS FILES
"""

TEMPLATE_VERSION_PREFIX = "# Template-Version:"
PATTERN_BLOCK_BEGIN = "# BEGIN WORKFLOWS STATUS FILES"
PATTERN_BLOCK_END = "# END WORKFLOWS STATUS FILES"
SEPARATOR_LINE = "# ============================================================================="

LOGGER = logging.getLogger(__name__)


class TemplateBlockError(RuntimeError):
    """Raised when expected template sentinel markers are missing."""


class MissingTemplateMarkerError(TemplateBlockError):
    """Raised when required markers are absent."""


def _read_template_lines() -> list[str] | None:
    template_path = Path(__file__).parent.parent / "templates/consumer-repo/.gitignore"
    if not template_path.exists():
        return None
    return template_path.read_text(encoding="utf-8").splitlines()


def _raise_template_error(message: str, *, missing: bool = False) -> NoReturn:
    LOGGER.critical("Template sentinel validation failed: %s", message)
    if missing:
        raise MissingTemplateMarkerError(message)
    raise TemplateBlockError(message)


def _validate_template_markers(lines: list[str]) -> tuple[int, int, int]:
    version_index = next(
        (idx for idx, line in enumerate(lines) if line.strip().startswith(TEMPLATE_VERSION_PREFIX)),
        None,
    )
    start = next(
        (idx for idx, line in enumerate(lines) if line.strip() == PATTERN_BLOCK_BEGIN),
        None,
    )
    end = next(
        (idx for idx, line in enumerate(lines) if line.strip() == PATTERN_BLOCK_END),
        None,
    )
    missing = []
    if version_index is None:
        missing.append("missing template version marker")
    if start is None:
        missing.append("missing status block begin marker")
    if end is None:
        missing.append("missing status block end marker")
    if missing:
        _raise_template_error(", ".join(missing), missing=True)
    assert version_index is not None
    assert start is not None
    assert end is not None
    if end <= start or version_index > start:
        _raise_template_error("status block markers are out of order")
    return version_index, start, end


def _load_template_patterns() -> list[str]:
    lines = _read_template_lines()
    if lines is None:
        return []
    try:
        _, start, end = _validate_template_markers(lines)
    except TemplateBlockError:
        return []
    patterns: list[str] = []
    for line in lines[start + 1 : end]:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        patterns.append(stripped)
    return patterns


CANONICAL_PATTERNS: list[str] = _load_template_patterns() or FALLBACK_PATTERNS
LEGACY_CONFLICTING_PATTERNS = frozenset({"node_modules/"})
VENDORED_NODE_MODULE_EXCEPTIONS = frozenset(
    {
        "!/.github/scripts/node_modules/",
        "!/.github/scripts/node_modules/**",
    }
)
PACKAGE_DEPENDENCY_SECTIONS = (
    "dependencies",
    "devDependencies",
    "optionalDependencies",
    "peerDependencies",
)


def _package_payload_declares_vendored_node_modules(payload: Any) -> bool:
    """Return whether a package manifest deliberately references a vendored dependency."""
    if not isinstance(payload, dict):
        return False
    for section_name in PACKAGE_DEPENDENCY_SECTIONS:
        section = payload.get(section_name)
        if not isinstance(section, dict):
            continue
        if any(
            isinstance(value, str) and value.strip().startswith("file:node_modules/")
            for value in section.values()
        ):
            return True
    return False


def package_declares_vendored_node_modules(repo_root: Path) -> bool:
    """Inspect the consumer package manifest that owns the targeted vendored tree."""
    package_path = Path(repo_root) / ".github/scripts/package.json"
    try:
        payload = json.loads(package_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError):
        return False
    return _package_payload_declares_vendored_node_modules(payload)


def canonical_patterns(*, preserve_vendored_node_modules: bool = True) -> list[str]:
    """Return canonical patterns specialized to the consumer dependency layout."""
    if preserve_vendored_node_modules:
        return list(CANONICAL_PATTERNS)
    return [
        pattern for pattern in CANONICAL_PATTERNS if pattern not in VENDORED_NODE_MODULE_EXCEPTIONS
    ]


def load_template_gitignore() -> str:
    """Load the full .gitignore template content."""
    template_path = Path(__file__).parent.parent / "templates/consumer-repo/.gitignore"
    if template_path.exists():
        return template_path.read_text(encoding="utf-8")
    # Fallback to generating from patterns
    return generate_minimal_block()


def load_template_block(*, preserve_vendored_node_modules: bool = True) -> str:
    """Load the shared status file .gitignore block from the template."""
    lines = _read_template_lines()
    if lines is None:
        return generate_minimal_block(preserve_vendored_node_modules=preserve_vendored_node_modules)
    try:
        _validate_template_markers(lines)
    except MissingTemplateMarkerError:
        raise
    except TemplateBlockError:
        return generate_minimal_block(preserve_vendored_node_modules=preserve_vendored_node_modules)
    header_index = next(
        (
            idx
            for idx, line in enumerate(lines)
            if "Workflows Consumer Repo - Shared Status Files" in line
        ),
        None,
    )
    try:
        if header_index is None:
            _raise_template_error("missing shared status files header")
        start = next(
            (idx for idx in range(header_index, -1, -1) if lines[idx].strip() == SEPARATOR_LINE),
            header_index,
        )
        end_marker_index = next(
            (
                idx
                for idx in range(header_index, len(lines))
                if lines[idx].strip() == PATTERN_BLOCK_END
            ),
            None,
        )
        if end_marker_index is None:
            _raise_template_error("missing status block end marker")
        end = next(
            (
                idx
                for idx in range(end_marker_index + 1, len(lines))
                if lines[idx].strip() == SEPARATOR_LINE
            ),
            None,
        )
        if end is None or not (start < header_index < end_marker_index < end):
            _raise_template_error("invalid status block boundary ordering")
    except TemplateBlockError:
        return generate_minimal_block(preserve_vendored_node_modules=preserve_vendored_node_modules)
    block_lines = lines[start:end]
    if not preserve_vendored_node_modules:
        block_lines = [
            line for line in block_lines if line.strip() not in VENDORED_NODE_MODULE_EXCEPTIONS
        ]
    return "\n".join(block_lines).rstrip("\n") + "\n"


def generate_minimal_block(*, preserve_vendored_node_modules: bool = True) -> str:
    """Generate minimal .gitignore block from canonical patterns."""
    lines = [GITIGNORE_BLOCK_HEADER.strip()]
    for pattern in canonical_patterns(
        preserve_vendored_node_modules=preserve_vendored_node_modules
    ):
        lines.append(pattern)
    lines.append(PATTERN_BLOCK_END)
    return "\n".join(lines) + "\n"


def _managed_block_span(lines: list[str]) -> tuple[int, int] | None:
    """Locate an existing managed block in a consumer .gitignore as (start, end_inclusive).

    The span deliberately includes the separator-bounded HEADER above the BEGIN marker, mirroring
    load_template_block's own boundaries, so a re-apply replaces the whole managed region instead
    of leaving a stale header (and a stale Template-Version) stranded above a fresh block. The
    header is only consumed when its identifying line is actually found, so a repo-local comment
    sitting above the block is never swallowed.
    """
    begins = [idx for idx, line in enumerate(lines) if line.strip() == PATTERN_BLOCK_BEGIN]
    ends = [idx for idx, line in enumerate(lines) if line.strip() == PATTERN_BLOCK_END]
    if not begins and not ends:
        return None
    if len(begins) != 1 or len(ends) != 1 or begins[0] >= ends[0]:
        raise TemplateBlockError(
            "Invalid managed block markers: require exactly one BEGIN marker followed by "
            "exactly one END marker"
        )
    begin, end = begins[0], ends[0]
    header = next(
        (
            idx
            for idx in range(begin, -1, -1)
            if "Workflows Consumer Repo - Shared Status Files" in lines[idx]
        ),
        None,
    )
    start = begin
    if header is not None:
        separator = next(
            (idx for idx in range(header, -1, -1) if lines[idx].strip() == SEPARATOR_LINE),
            None,
        )
        if separator is not None:
            start = separator
    return start, end


def apply_block_to_file(
    gitignore_path: Path,
    *,
    dry_run: bool = False,
    preserve_vendored_node_modules: bool | None = None,
) -> dict[str, object]:
    """Idempotently merge the managed block into a consumer repo's .gitignore.

    Replace-in-place when the block is already there and append when it is not. Preserve repo-local
    rules except for exact legacy patterns known to defeat a canonical replacement. In particular,
    remove a repo-local bare ``node_modules/`` rule. The managed block supplies the all-depth
    ignore and retains targeted exceptions only when ``.github/scripts/package.json`` declares
    a deliberate ``file:node_modules/`` dependency.
    Writing only on a real change keeps a scheduled sync a no-op when there is nothing to do.

    When ``dry_run`` is true, report whether a write would occur without mutating the file so
    maint-68 dry consumer runs can still set ``has_changes`` and list ``.gitignore`` in the
    sync summary.
    """
    path = Path(gitignore_path)
    if preserve_vendored_node_modules is None:
        preserve_vendored_node_modules = package_declares_vendored_node_modules(path.parent)
    block = load_template_block(
        preserve_vendored_node_modules=preserve_vendored_node_modules
    ).rstrip("\n")
    existing = path.read_bytes().decode("utf-8") if path.is_file() else ""
    newline = "\r\n" if "\r\n" in existing else "\n"
    lines = existing.splitlines()

    span = _managed_block_span(lines)

    def without_conflicts(repo_lines: list[str]) -> list[str]:
        conflicts = set(LEGACY_CONFLICTING_PATTERNS)
        if not preserve_vendored_node_modules:
            conflicts.update(VENDORED_NODE_MODULE_EXCEPTIONS)
        return [line for line in repo_lines if line.strip() not in conflicts]

    if span is not None:
        start, end = span
        merged = (
            without_conflicts(lines[:start])
            + block.splitlines()
            + without_conflicts(lines[end + 1 :])
        )
        action = "replaced"
    elif lines:
        repo_lines = without_conflicts(lines)
        merged = repo_lines + ([""] if repo_lines and repo_lines[-1].strip() else [])
        merged += block.splitlines()
        action = "appended"
    else:
        merged = block.splitlines()
        action = "created"

    updated = newline.join(merged).rstrip("\r\n") + newline
    changed = updated != existing
    if changed and not dry_run:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(updated, encoding="utf-8")
    return {"path": str(path), "action": action if changed else "unchanged", "changed": changed}


def check_gitignore_content(
    content: str, *, preserve_vendored_node_modules: bool = True
) -> dict[str, bool]:
    """Check which canonical patterns are present in .gitignore content."""
    # Normalize: remove comments and empty lines for comparison
    lines = set()
    for line in content.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            lines.add(stripped)

    return {
        pattern: pattern in lines
        for pattern in canonical_patterns(
            preserve_vendored_node_modules=preserve_vendored_node_modules
        )
    }


def get_missing_patterns(content: str, *, preserve_vendored_node_modules: bool = True) -> list[str]:
    """Get list of canonical patterns missing from .gitignore."""
    status = check_gitignore_content(
        content, preserve_vendored_node_modules=preserve_vendored_node_modules
    )
    return [pattern for pattern, present in status.items() if not present]


def get_conflicting_patterns(
    content: str, *, preserve_vendored_node_modules: bool = True
) -> list[str]:
    """Return legacy rules ordered after the managed vendored-tree exceptions."""
    patterns = [
        line.strip()
        for line in content.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]
    if not preserve_vendored_node_modules:
        return sorted(pattern for pattern in VENDORED_NODE_MODULE_EXCEPTIONS if pattern in patterns)
    required_exceptions = VENDORED_NODE_MODULE_EXCEPTIONS
    last_conflict = max(
        (index for index, pattern in enumerate(patterns) if pattern in LEGACY_CONFLICTING_PATTERNS),
        default=-1,
    )
    last_exceptions = {
        pattern: max(
            (index for index, candidate in enumerate(patterns) if candidate == pattern),
            default=-1,
        )
        for pattern in required_exceptions
    }
    if last_conflict >= 0 and any(index < last_conflict for index in last_exceptions.values()):
        return sorted(LEGACY_CONFLICTING_PATTERNS)
    return []


def generate_append_block(missing: list[str]) -> str:
    """Generate a .gitignore block for missing patterns only."""
    if not missing:
        return ""

    lines = [
        "",
        "# --- Workflows Shared Status Files (auto-synced) ---",
        "# Prevents merge conflicts from workflow-generated files",
    ]
    lines.extend(missing)
    return "\n".join(lines) + "\n"


def print_check_report(
    content: str,
    repo_name: str = "local",
    *,
    preserve_vendored_node_modules: bool = True,
) -> int:
    """Print a report of pattern coverage and return exit code."""
    expected_patterns = canonical_patterns(
        preserve_vendored_node_modules=preserve_vendored_node_modules
    )
    status = check_gitignore_content(
        content, preserve_vendored_node_modules=preserve_vendored_node_modules
    )
    missing = [p for p, present in status.items() if not present]
    conflicting = get_conflicting_patterns(
        content, preserve_vendored_node_modules=preserve_vendored_node_modules
    )
    present = [p for p, present in status.items() if present]

    print(f"\n=== Status File .gitignore Check: {repo_name} ===\n")

    if present:
        print(f"✓ Present ({len(present)}/{len(expected_patterns)}):")
        for p in present:
            print(f"  ✓ {p}")

    if missing:
        print(f"\n✗ Missing ({len(missing)}/{len(expected_patterns)}):")
        for p in missing:
            print(f"  ✗ {p}")
        print("\nTo fix, add these patterns to .gitignore:")
        print(generate_append_block(missing))
    if conflicting:
        print("\n✗ Conflicting legacy patterns:")
        for pattern in conflicting:
            print(f"  ✗ {pattern}")
        print("\nRemove these exact rules; the managed block contains their safe replacements.")

    if missing or conflicting:
        return 1

    print("\n✓ All canonical patterns present!")
    return 0


def decode_repo_gitignore(encoded: str, repo: str) -> str | None:
    """Decode base64 gitignore content fetched from the GitHub API."""
    return decode_repo_file(encoded, repo, ".gitignore")


def decode_repo_file(encoded: str, repo: str, path: str) -> str | None:
    """Decode base64 repository content fetched from the GitHub API."""
    if not encoded:
        print(f"Error fetching {path} from {repo}: empty response", file=sys.stderr)
        return None
    sanitized = "".join(encoded.split())
    try:
        decoded_bytes = base64.b64decode(sanitized, validate=True)
    except (binascii.Error, ValueError) as exc:
        print(f"Error decoding {path} from {repo}: {exc}", file=sys.stderr)
        return None
    try:
        return decoded_bytes.decode()
    except UnicodeDecodeError as exc:
        print(f"Error decoding {path} from {repo}: {exc}", file=sys.stderr)
        return None


def main() -> int:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Sync shared status file .gitignore patterns",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check local .gitignore for missing patterns",
    )
    parser.add_argument(
        "--apply",
        metavar="GITIGNORE_PATH",
        help=(
            "Merge the managed block into a checked-out consumer .gitignore, in place. "
            "Idempotent: replaces an existing block, appends when absent, writes only on change, "
            "and never touches repo-local rules outside the managed region."
        ),
    )
    parser.add_argument(
        "--repo",
        help="GitHub repo (owner/name) to check via API",
    )
    parser.add_argument(
        "--print-block",
        action="store_true",
        help="Print the canonical .gitignore block",
    )
    parser.add_argument(
        "--print-patterns",
        action="store_true",
        help="Print just the pattern list (one per line)",
    )
    parser.add_argument(
        "--gitignore-path",
        type=Path,
        help="Path to local .gitignore to check",
    )

    args = parser.parse_args()

    if args.print_block:
        try:
            print(
                load_template_block(
                    preserve_vendored_node_modules=package_declares_vendored_node_modules(
                        Path.cwd()
                    )
                ),
                end="",
            )
        except TemplateBlockError as exc:
            print(f"Error: {exc}", file=sys.stderr)
            return 1
        return 0

    if args.print_patterns:
        for pattern in CANONICAL_PATTERNS:
            print(pattern)
        return 0

    if args.gitignore_path:
        if not args.gitignore_path.exists():
            print(f"Error: {args.gitignore_path} not found", file=sys.stderr)
            return 1
        content = args.gitignore_path.read_text()
        preserve_vendored = package_declares_vendored_node_modules(args.gitignore_path.parent)
        return print_check_report(
            content,
            str(args.gitignore_path),
            preserve_vendored_node_modules=preserve_vendored,
        )

    if args.check:
        # Check local repo's .gitignore
        local_gitignore = Path(".gitignore")
        if not local_gitignore.exists():
            print("No .gitignore found in current directory", file=sys.stderr)
            return 1
        content = local_gitignore.read_text()
        return print_check_report(
            content,
            "local",
            preserve_vendored_node_modules=package_declares_vendored_node_modules(Path.cwd()),
        )

    if args.apply:
        apply_result = apply_block_to_file(Path(args.apply))
        print(f"{apply_result['action']}: {apply_result['path']}")
        return 0

    if args.repo:
        # Check remote repo via GitHub API
        result = subprocess.run(
            [
                "gh",
                "api",
                f"repos/{args.repo}/contents/.gitignore",
                "--jq",
                ".content",
            ],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            print(f"Error fetching .gitignore from {args.repo}", file=sys.stderr)
            print(result.stderr, file=sys.stderr)
            return 1

        content = decode_repo_gitignore(result.stdout.strip(), args.repo)
        if content is None:
            return 1

        package_path = ".github/scripts/package.json"
        package_result = subprocess.run(
            [
                "gh",
                "api",
                f"repos/{args.repo}/contents/{package_path}",
                "--jq",
                ".content",
            ],
            capture_output=True,
            text=True,
        )
        preserve_vendored = False
        if package_result.returncode == 0:
            package_content = decode_repo_file(
                package_result.stdout.strip(), args.repo, package_path
            )
            if package_content is None:
                return 1
            try:
                package_payload = json.loads(package_content)
            except json.JSONDecodeError as exc:
                print(f"Error parsing {package_path} from {args.repo}: {exc}", file=sys.stderr)
                return 1
            preserve_vendored = _package_payload_declares_vendored_node_modules(package_payload)
        elif "404" not in package_result.stderr:
            print(f"Error fetching {package_path} from {args.repo}", file=sys.stderr)
            print(package_result.stderr, file=sys.stderr)
            return 1

        return print_check_report(
            content,
            args.repo,
            preserve_vendored_node_modules=preserve_vendored,
        )

    # Default: print help
    parser.print_help()
    return 0


if __name__ == "__main__":
    sys.exit(main())
